name: 'Build and Deploy '
on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title for the release'
        required: false
      # version:
      #   description: 'Version to release'
      #   required: true
      description:
        description: 'Description for the release'
        required: false

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: Setup GIT
        run: |
          git config --global user.name "github.actor"

      # - name: Bump version
      #   id: updated_version
      #   run: |
      #     cd server
      #     npm version patch
      #     curr_version="$(node -p "require('./package.json').version")"
      #     cd ..
      #     git add -A
      #     git commit -m $curr_version
      #     git push https://${{secrets.GA_REPO_TOKEN}}@github.com/opstronomy/ops-chat-server
      #     echo The version is $curr_version
      #     echo "::set-output name=version::$curr_version"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: "Publish to GHCR"
      #   run: |
      #     cd server
      #     npm run-script publish:ghcr

      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_JSON }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "${{ secrets.PROJECT_ID }}"

      - name: Install gcloud SDK and kubectl
        run: |
          curl -sSL https://sdk.cloud.google.com | bash
          exec -l $SHELL
          gcloud components install kubectl 

      - name: Enable Cloud Run API
        run: gcloud services enable run.googleapis.com       

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ secrets.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Pull Docker image from Artifact Registry
        run: |
          docker pull asia-south1-docker.pkg.dev/practise-414115/hasura/hasura/graphql-engine


      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
    # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
         # replacing the image name in the k8s template
          ./kustomize edit set image asia-south1-docker.pkg.dev/practise-414115/hasura/hasura/graphql-engine=asia-south1-docker.pkg.dev/practise-414115/hasura/hasura/graphql-engine
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/hasura
          kubectl get services -o wide   

      # - name: Deploy to GKE Autopilot
      #   run: |
      #     gcloud container clusters get-credentials opstronomy --region asia-south1
      #     gcloud run deploy hasura --image asia-south1-docker.pkg.dev/practise-414115/hasura/hasura/graphql-engine --platform managed --region asia-south1
     
