name: 'Deploy to GKE Autopilot'
on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title for the release'
        required: false
      description:
        description: 'Description for the release'
        required: false

jobs:
  deploy:
    name: 'Deploy to GKE Autopilot'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Authenticate with Google Cloud"
        uses: google-github-actions/auth@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "${{ secrets.PROJECT_ID }}"

      - name: "Configure kubectl"
        run: gcloud container clusters get-credentials opstronomy --region asia-south1 --quiet

      - name: "Deploy to GKE Autopilot"
        run: |
          kubectl set image deployment/hasura hasura=asia-south1-docker.pkg.dev/practise-414115/hasura/hasura/graphql-engine:latest

      - name: "Verify Deployment"
        run: kubectl rollout status deployment/hasura
