name: 'Build and Deploy '
on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title for the release'
        required: false
      description:
        description: 'Description for the release'
        required: false

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: Setup GIT
        run: |
          git config --global user.name "github.actor"

      # Uncomment and modify this section if you want to bump the version
      # - name: Bump version
      #   id: updated_version
      #   run: |
      #     cd server
      #     npm version patch
      #     curr_version="$(node -p "require('./package.json').version")"
      #     cd ..
      #     git add -A
      #     git commit -m $curr_version
      #     git push https://${{secrets.GA_REPO_TOKEN}}@github.com/opstronomy/ops-chat-server
      #     echo The version is $curr_version
      #     echo "::set-output name=version::$curr_version"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Uncomment this section if you need to publish to GitHub Container Registry
      # - name: "Publish to GHCR"
      #   run: |
      #     cd server
      #     npm run-script publish:ghcr

      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_JSON }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "${{ secrets.PROJECT_ID }}"

      - name: Install gcloud SDK and kubectl
        run: |
          curl -sSL https://sdk.cloud.google.com | bash
          exec -l $SHELL
          gcloud components install kubectl 

      # Install gke-gcloud-auth-plugin if needed
      # - name: "Install gke-gcloud-auth-plugin"
      #   run: |
      #     gcloud components install kubectl
      #     gcloud components install gke-gcloud-auth-plugin       

      - name: "Configure kubectl"
        run: |
          gcloud container clusters get-credentials opstronomy --region asia-south1 --quiet
          kubectl version --short

      - name: "Deploy to GKE Autopilot"
        run: |
          # Add your deployment command here. Modify it according to your needs.
          # Replace "hasura" with your deployment name and the image URL with your actual image.
          kubectl set image deployment/hasura hasura=asia-south1-docker.pkg.dev/practise-414115/hasura/hasura/graphql-engine:latest

      - name: "Verify Deployment"
        run: |
          # Add any verification steps here, such as checking the rollout status.
          kubectl get deployments
          kubectl rollout status deployment/hasura
