name: 'Build and Deploy '
on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title for the release'
        required: false
      # version:
      #   description: 'Version to release'
      #   required: true
      description:
        description: 'Description for the release'
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to GCP Kubernetes Autopilot
      run: |
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --region ${{ secrets.GCP_CLUSTER_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}
        gcloud container clusters update ${{ secrets.GCP_CLUSTER_NAME }} --update-addons=HttpLoadBalancing=ENABLED
        gcloud container clusters update ${{ secrets.GCP_CLUSTER_NAME }} --region ${{ secrets.GCP_CLUSTER_REGION }} --project ${{ secrets.GCP_PROJECT_ID }} --image-type "COS_CONTAINERD"
        gcloud container clusters update ${{ secrets.GCP_CLUSTER_NAME }} --region ${{ secrets.GCP_CLUSTER_REGION }} --project ${{ secrets.GCP_PROJECT_ID }} --enable-autoupgrade
        gcloud container clusters update ${{ secrets.GCP_CLUSTER_NAME }} --region ${{ secrets.GCP_CLUSTER_REGION }} --project ${{ secrets.GCP_PROJECT_ID }} --enable-autorepair