name: 'Deploy New Version'
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Get GCP Kubernetes Autopilot cluster credentials
      uses: google-github-actions/get-gke-credentials@v0.3.0
      with:
        cluster_name: ${{ secrets.GCP_CLUSTER_NAME }}
        location: ${{ secrets.GCP_CLUSTER_REGION }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Create deployment if it doesn't exist
      run: |
        if ! kubectl get deployments/my-app; then
          kubectl create deployment my-app --image=asia-south1-docker.pkg.dev/practise-414115/hasura/hasura/graphql-engine:latest
        fi

    - name: Set environment variables
      run: |
       kubectl set env deployment/my-app HASURA_GRAPHQL_ADMIN_SECRET='opstronomy' HASURA_GRAPHQL_DEV_MODE='true' HASURA_GRAPHQL_ENABLED_LOG_TYPES='startup,http-log' HASURA_GRAPHQL_ENABLE_CONSOLE='true' HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS='true' HASURA_GRAPHQL_METADATA_DATABASE_URL='postgres://test:Opstronomy1234@34.93.127.79:5432/postgres' VAR8='8080'

    - name: Deploy new version to GCP Kubernetes Autopilot latest tag
      run: |
       kubectl set image deployment/my-app my-app=asia-south1-docker.pkg.dev/practise-414115/hasura/hasura/graphql-engine:latest